// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGVtNtAcZBAotWBr29qZ6cmkyZuQVWSU8',
    appId: '1:1033660514515:web:99a231bd49a9041be25426',
    messagingSenderId: '1033660514515',
    projectId: 'kml-chat-app',
    authDomain: 'kml-chat-app.firebaseapp.com',
    storageBucket: 'kml-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7HHuYEB4ieAoNXN6dIznFCaoqJgt43GU',
    appId: '1:1033660514515:android:34f4c2914eb0cbc9e25426',
    messagingSenderId: '1033660514515',
    projectId: 'kml-chat-app',
    storageBucket: 'kml-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqbt8PBJdoSCbXuoUIoPIV36PxPFeQLqI',
    appId: '1:1033660514515:ios:b85116f358bd9960e25426',
    messagingSenderId: '1033660514515',
    projectId: 'kml-chat-app',
    storageBucket: 'kml-chat-app.appspot.com',
    iosClientId: '1033660514515-l796gklnnt3ps25viuumnfl6n3u1hta7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqbt8PBJdoSCbXuoUIoPIV36PxPFeQLqI',
    appId: '1:1033660514515:ios:b85116f358bd9960e25426',
    messagingSenderId: '1033660514515',
    projectId: 'kml-chat-app',
    storageBucket: 'kml-chat-app.appspot.com',
    iosClientId: '1033660514515-l796gklnnt3ps25viuumnfl6n3u1hta7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
